server:
  port: 8888

#acessar uris
#spring:
#  cloud:
#    config:
#      server:
#        git:
#          uri: https://github.com/carledwin/microservice-repo
#          search-paths: fornecedor

#profile local
spring:
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: ../microservice-repo